//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(ArrangedMarriage.CLASS_NAME, typeof(ArrangedMarriage))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type ArrangedMarriage.
    /// </summary>
    public partial class ArrangedMarriage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.ArrangedMarriage";


        /// <summary>
        /// The instance of the class that provides extended API for working with ArrangedMarriage fields.
        /// </summary>
        private readonly ArrangedMarriageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ArrangedMarriageID.
        /// </summary>
        [DatabaseIDField]
        public int ArrangedMarriageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ArrangedMarriageID"), 0);
            }
            set
            {
                SetValue("ArrangedMarriageID", value);
            }
        }


        /// <summary>
        /// Menu Name.
        /// </summary>
        [DatabaseField]
        public string MenuName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MenuName"), @"");
            }
            set
            {
                SetValue("MenuName", value);
            }
        }


        /// <summary>
        /// Car.
        /// </summary>
        [DatabaseField]
        public string CarName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CarName"), @"");
            }
            set
            {
                SetValue("CarName", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ArrangedMarriage fields.
        /// </summary>
        [RegisterProperty]
        public ArrangedMarriageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ArrangedMarriage fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ArrangedMarriageFields : AbstractHierarchicalObject<ArrangedMarriageFields>
        {
            /// <summary>
            /// The content item of type ArrangedMarriage that is a target of the extended API.
            /// </summary>
            private readonly ArrangedMarriage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ArrangedMarriageFields" /> class with the specified content item of type ArrangedMarriage.
            /// </summary>
            /// <param name="instance">The content item of type ArrangedMarriage that is a target of the extended API.</param>
            public ArrangedMarriageFields(ArrangedMarriage instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ArrangedMarriageID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ArrangedMarriageID;
                }
                set
                {
                    mInstance.ArrangedMarriageID = value;
                }
            }


            /// <summary>
            /// Menu Name.
            /// </summary>
            public string MenuName
            {
                get
                {
                    return mInstance.MenuName;
                }
                set
                {
                    mInstance.MenuName = value;
                }
            }


            /// <summary>
            /// Car.
            /// </summary>
            public string CarName
            {
                get
                {
                    return mInstance.CarName;
                }
                set
                {
                    mInstance.CarName = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ArrangedMarriage" /> class.
        /// </summary>
        public ArrangedMarriage() : base(CLASS_NAME)
        {
            mFields = new ArrangedMarriageFields(this);
        }

        #endregion
    }
}