//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(HolyMatrimony.CLASS_NAME, typeof(HolyMatrimony))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type HolyMatrimony.
    /// </summary>
    public partial class HolyMatrimony : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.HolyMatrimony";


        /// <summary>
        /// The instance of the class that provides extended API for working with HolyMatrimony fields.
        /// </summary>
        private readonly HolyMatrimonyFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// HolyMatrimonyID.
        /// </summary>
        [DatabaseIDField]
        public int HolyMatrimonyID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("HolyMatrimonyID"), 0);
            }
            set
            {
                SetValue("HolyMatrimonyID", value);
            }
        }


        /// <summary>
        /// Menu Name.
        /// </summary>
        [DatabaseField]
        public string MenuName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MenuName"), @"");
            }
            set
            {
                SetValue("MenuName", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with HolyMatrimony fields.
        /// </summary>
        [RegisterProperty]
        public HolyMatrimonyFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with HolyMatrimony fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class HolyMatrimonyFields : AbstractHierarchicalObject<HolyMatrimonyFields>
        {
            /// <summary>
            /// The content item of type HolyMatrimony that is a target of the extended API.
            /// </summary>
            private readonly HolyMatrimony mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="HolyMatrimonyFields" /> class with the specified content item of type HolyMatrimony.
            /// </summary>
            /// <param name="instance">The content item of type HolyMatrimony that is a target of the extended API.</param>
            public HolyMatrimonyFields(HolyMatrimony instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// HolyMatrimonyID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.HolyMatrimonyID;
                }
                set
                {
                    mInstance.HolyMatrimonyID = value;
                }
            }


            /// <summary>
            /// Menu Name.
            /// </summary>
            public string MenuName
            {
                get
                {
                    return mInstance.MenuName;
                }
                set
                {
                    mInstance.MenuName = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="HolyMatrimony" /> class.
        /// </summary>
        public HolyMatrimony() : base(CLASS_NAME)
        {
            mFields = new HolyMatrimonyFields(this);
        }

        #endregion
    }
}