//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Inbreeding.CLASS_NAME, typeof(Inbreeding))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type Inbreeding.
    /// </summary>
    public partial class Inbreeding : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.Inbreeding";


        /// <summary>
        /// The instance of the class that provides extended API for working with Inbreeding fields.
        /// </summary>
        private readonly InbreedingFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// InbreedingID.
        /// </summary>
        [DatabaseIDField]
        public int InbreedingID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("InbreedingID"), 0);
            }
            set
            {
                SetValue("InbreedingID", value);
            }
        }


        /// <summary>
        /// Name.
        /// </summary>
        [DatabaseField]
        public string MenuName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MenuName"), @"");
            }
            set
            {
                SetValue("MenuName", value);
            }
        }


        /// <summary>
        /// Related Link 1.
        /// </summary>
        [DatabaseField]
        public string RelatedLink1Text
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink1Text"), @"");
            }
            set
            {
                SetValue("RelatedLink1Text", value);
            }
        }


        /// <summary>
        /// Related Link 1 Url.
        /// </summary>
        [DatabaseField]
        public string RelatedLink1Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink1Url"), @"");
            }
            set
            {
                SetValue("RelatedLink1Url", value);
            }
        }


        /// <summary>
        /// Related Link 2 Text.
        /// </summary>
        [DatabaseField]
        public string RelatedLink2Text
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink2Text"), @"");
            }
            set
            {
                SetValue("RelatedLink2Text", value);
            }
        }


        /// <summary>
        /// Related Link 2 Url.
        /// </summary>
        [DatabaseField]
        public string RelatedLink2Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink2Url"), @"");
            }
            set
            {
                SetValue("RelatedLink2Url", value);
            }
        }


        /// <summary>
        /// Related Link 3 Text.
        /// </summary>
        [DatabaseField]
        public string RelatedLink3Text
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink3Text"), @"");
            }
            set
            {
                SetValue("RelatedLink3Text", value);
            }
        }


        /// <summary>
        /// Related Link 3 Url.
        /// </summary>
        [DatabaseField]
        public string RelatedLink3Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink3Url"), @"");
            }
            set
            {
                SetValue("RelatedLink3Url", value);
            }
        }


        /// <summary>
        /// Related Link 4.
        /// </summary>
        [DatabaseField]
        public string RelatedLink4Text
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink4Text"), @"");
            }
            set
            {
                SetValue("RelatedLink4Text", value);
            }
        }


        /// <summary>
        /// Related Link 4.
        /// </summary>
        [DatabaseField]
        public string RelatedLink4Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("RelatedLink4Url"), @"");
            }
            set
            {
                SetValue("RelatedLink4Url", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Inbreeding fields.
        /// </summary>
        [RegisterProperty]
        public InbreedingFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Inbreeding fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class InbreedingFields : AbstractHierarchicalObject<InbreedingFields>
        {
            /// <summary>
            /// The content item of type Inbreeding that is a target of the extended API.
            /// </summary>
            private readonly Inbreeding mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="InbreedingFields" /> class with the specified content item of type Inbreeding.
            /// </summary>
            /// <param name="instance">The content item of type Inbreeding that is a target of the extended API.</param>
            public InbreedingFields(Inbreeding instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// InbreedingID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.InbreedingID;
                }
                set
                {
                    mInstance.InbreedingID = value;
                }
            }


            /// <summary>
            /// Name.
            /// </summary>
            public string MenuName
            {
                get
                {
                    return mInstance.MenuName;
                }
                set
                {
                    mInstance.MenuName = value;
                }
            }


            /// <summary>
            /// Related Link 1.
            /// </summary>
            public string RelatedLink1Text
            {
                get
                {
                    return mInstance.RelatedLink1Text;
                }
                set
                {
                    mInstance.RelatedLink1Text = value;
                }
            }


            /// <summary>
            /// Related Link 1 Url.
            /// </summary>
            public string RelatedLink1Url
            {
                get
                {
                    return mInstance.RelatedLink1Url;
                }
                set
                {
                    mInstance.RelatedLink1Url = value;
                }
            }


            /// <summary>
            /// Related Link 2 Text.
            /// </summary>
            public string RelatedLink2Text
            {
                get
                {
                    return mInstance.RelatedLink2Text;
                }
                set
                {
                    mInstance.RelatedLink2Text = value;
                }
            }


            /// <summary>
            /// Related Link 2 Url.
            /// </summary>
            public string RelatedLink2Url
            {
                get
                {
                    return mInstance.RelatedLink2Url;
                }
                set
                {
                    mInstance.RelatedLink2Url = value;
                }
            }


            /// <summary>
            /// Related Link 3 Text.
            /// </summary>
            public string RelatedLink3Text
            {
                get
                {
                    return mInstance.RelatedLink3Text;
                }
                set
                {
                    mInstance.RelatedLink3Text = value;
                }
            }


            /// <summary>
            /// Related Link 3 Url.
            /// </summary>
            public string RelatedLink3Url
            {
                get
                {
                    return mInstance.RelatedLink3Url;
                }
                set
                {
                    mInstance.RelatedLink3Url = value;
                }
            }


            /// <summary>
            /// Related Link 4.
            /// </summary>
            public string RelatedLink4Text
            {
                get
                {
                    return mInstance.RelatedLink4Text;
                }
                set
                {
                    mInstance.RelatedLink4Text = value;
                }
            }


            /// <summary>
            /// Related Link 4.
            /// </summary>
            public string RelatedLink4Url
            {
                get
                {
                    return mInstance.RelatedLink4Url;
                }
                set
                {
                    mInstance.RelatedLink4Url = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Inbreeding" /> class.
        /// </summary>
        public Inbreeding() : base(CLASS_NAME)
        {
            mFields = new InbreedingFields(this);
        }

        #endregion
    }
}