//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Meme.CLASS_NAME, typeof(Meme))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type Meme.
    /// </summary>
    public partial class Meme : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.Meme";


        /// <summary>
        /// The instance of the class that provides extended API for working with Meme fields.
        /// </summary>
        private readonly MemeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// MemeID.
        /// </summary>
        [DatabaseIDField]
        public int MemeID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("MemeID"), 0);
            }
            set
            {
                SetValue("MemeID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string MemeTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MemeTitle"), @"");
            }
            set
            {
                SetValue("MemeTitle", value);
            }
        }


        /// <summary>
        /// Meme Url.
        /// </summary>
        [DatabaseField]
        public string ImageUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ImageUrl"), @"");
            }
            set
            {
                SetValue("ImageUrl", value);
            }
        }


        /// <summary>
        /// Type.
        /// </summary>
        public string MemeType
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MemeType"), @"");
            }
            set
            {
                SetValue("MemeType", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Meme fields.
        /// </summary>
        [RegisterProperty]
        public MemeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Meme fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class MemeFields : AbstractHierarchicalObject<MemeFields>
        {
            /// <summary>
            /// The content item of type Meme that is a target of the extended API.
            /// </summary>
            private readonly Meme mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="MemeFields" /> class with the specified content item of type Meme.
            /// </summary>
            /// <param name="instance">The content item of type Meme that is a target of the extended API.</param>
            public MemeFields(Meme instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// MemeID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.MemeID;
                }
                set
                {
                    mInstance.MemeID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.MemeTitle;
                }
                set
                {
                    mInstance.MemeTitle = value;
                }
            }


            /// <summary>
            /// Meme Url.
            /// </summary>
            public string ImageUrl
            {
                get
                {
                    return mInstance.ImageUrl;
                }
                set
                {
                    mInstance.ImageUrl = value;
                }
            }


            /// <summary>
            /// Type.
            /// </summary>
            public string Type
            {
                get
                {
                    return mInstance.MemeType;
                }
                set
                {
                    mInstance.MemeType = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Meme" /> class.
        /// </summary>
        public Meme() : base(CLASS_NAME)
        {
            mFields = new MemeFields(this);
        }

        #endregion
    }
}