//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Polygomy.CLASS_NAME, typeof(Polygomy))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type Polygomy.
    /// </summary>
    public partial class Polygomy : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.Polygomy";


        /// <summary>
        /// The instance of the class that provides extended API for working with Polygomy fields.
        /// </summary>
        private readonly PolygomyFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PolygomyID.
        /// </summary>
        [DatabaseIDField]
        public int PolygomyID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PolygomyID"), 0);
            }
            set
            {
                SetValue("PolygomyID", value);
            }
        }


        /// <summary>
        /// Menu Name.
        /// </summary>
        [DatabaseField]
        public string MenuName
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MenuName"), @"");
            }
            set
            {
                SetValue("MenuName", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Polygomy fields.
        /// </summary>
        [RegisterProperty]
        public PolygomyFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Polygomy fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PolygomyFields : AbstractHierarchicalObject<PolygomyFields>
        {
            /// <summary>
            /// The content item of type Polygomy that is a target of the extended API.
            /// </summary>
            private readonly Polygomy mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PolygomyFields" /> class with the specified content item of type Polygomy.
            /// </summary>
            /// <param name="instance">The content item of type Polygomy that is a target of the extended API.</param>
            public PolygomyFields(Polygomy instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PolygomyID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PolygomyID;
                }
                set
                {
                    mInstance.PolygomyID = value;
                }
            }


            /// <summary>
            /// Menu Name.
            /// </summary>
            public string MenuName
            {
                get
                {
                    return mInstance.MenuName;
                }
                set
                {
                    mInstance.MenuName = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Polygomy" /> class.
        /// </summary>
        public Polygomy() : base(CLASS_NAME)
        {
            mFields = new PolygomyFields(this);
        }

        #endregion
    }
}