//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Song.CLASS_NAME, typeof(Song))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type Song.
    /// </summary>
    public partial class Song : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.Song";


        /// <summary>
        /// The instance of the class that provides extended API for working with Song fields.
        /// </summary>
        private readonly SongFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// SongsID.
        /// </summary>
        [DatabaseIDField]
        public int SongsID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SongsID"), 0);
            }
            set
            {
                SetValue("SongsID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string SongTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SongTitle"), @"");
            }
            set
            {
                SetValue("SongTitle", value);
            }
        }


        /// <summary>
        /// Song Author.
        /// </summary>
        [DatabaseField]
        public string SongAuthor
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SongAuthor"), @"");
            }
            set
            {
                SetValue("SongAuthor", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Song fields.
        /// </summary>
        [RegisterProperty]
        public SongFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Song fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class SongFields : AbstractHierarchicalObject<SongFields>
        {
            /// <summary>
            /// The content item of type Song that is a target of the extended API.
            /// </summary>
            private readonly Song mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="SongFields" /> class with the specified content item of type Song.
            /// </summary>
            /// <param name="instance">The content item of type Song that is a target of the extended API.</param>
            public SongFields(Song instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// SongsID.
            /// </summary>
            public int sID
            {
                get
                {
                    return mInstance.SongsID;
                }
                set
                {
                    mInstance.SongsID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.SongTitle;
                }
                set
                {
                    mInstance.SongTitle = value;
                }
            }


            /// <summary>
            /// Song Author.
            /// </summary>
            public string Author
            {
                get
                {
                    return mInstance.SongAuthor;
                }
                set
                {
                    mInstance.SongAuthor = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Song" /> class.
        /// </summary>
        public Song() : base(CLASS_NAME)
        {
            mFields = new SongFields(this);
        }

        #endregion
    }
}