//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.NEWCC;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Component_MetaData.CLASS_NAME, typeof(Component_MetaData))]

namespace CMS.DocumentEngine.Types.NEWCC
{
    /// <summary>
    /// Represents a content item of type Component_MetaData.
    /// </summary>
    public partial class Component_MetaData : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NEWCC.Component_MetaData";


        /// <summary>
        /// The instance of the class that provides extended API for working with Component_MetaData fields.
        /// </summary>
        private readonly Component_MetaDataFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Component_MetaDataID.
        /// </summary>
        [DatabaseIDField]
        public int Component_MetaDataID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("Component_MetaDataID"), 0);
            }
            set
            {
                SetValue("Component_MetaDataID", value);
            }
        }


        /// <summary>
        /// Page Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Abstract.
        /// </summary>
        [DatabaseField]
        public string Abstract
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Abstract"), @"");
            }
            set
            {
                SetValue("Abstract", value);
            }
        }


        /// <summary>
        /// Key words.
        /// </summary>
        [DatabaseField]
        public string Keywords
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Keywords"), @"");
            }
            set
            {
                SetValue("Keywords", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with Component_MetaData fields.
        /// </summary>
        [RegisterProperty]
        public Component_MetaDataFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with Component_MetaData fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class Component_MetaDataFields : AbstractHierarchicalObject<Component_MetaDataFields>
        {
            /// <summary>
            /// The content item of type Component_MetaData that is a target of the extended API.
            /// </summary>
            private readonly Component_MetaData mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="Component_MetaDataFields" /> class with the specified content item of type Component_MetaData.
            /// </summary>
            /// <param name="instance">The content item of type Component_MetaData that is a target of the extended API.</param>
            public Component_MetaDataFields(Component_MetaData instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Component_MetaDataID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.Component_MetaDataID;
                }
                set
                {
                    mInstance.Component_MetaDataID = value;
                }
            }


            /// <summary>
            /// Page Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Abstract.
            /// </summary>
            public string Abstract
            {
                get
                {
                    return mInstance.Abstract;
                }
                set
                {
                    mInstance.Abstract = value;
                }
            }


            /// <summary>
            /// Key words.
            /// </summary>
            public string Keywords
            {
                get
                {
                    return mInstance.Keywords;
                }
                set
                {
                    mInstance.Keywords = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="Component_MetaData" /> class.
        /// </summary>
        public Component_MetaData() : base(CLASS_NAME)
        {
            mFields = new Component_MetaDataFields(this);
        }

        #endregion
    }
}